{lib}: let
  # DOT / Mermaid の node id は、名前が identifier-safe な場合
  # (英数字・ハイフン・アンダースコアのみ) は元の名前をそのまま使い、
  # それ以外は "m<n>" にマップして label で元の名前を表示する。
  isSimple = n: builtins.match "[A-Za-z0-9_.-]+" n != null;

  mkNodeIds = names: let
    uniqueSorted = lib.unique (builtins.sort (a: b: a < b) names);
    simple = builtins.filter isSimple uniqueSorted;
    complex = builtins.filter (n: !isSimple n) uniqueSorted;

    /*
    complex 名には "m<n>" を割り当てるが、simple な node が既に
    まさにその文字列 (例: module 名が本当に "m0") を id として
    使っている場合、素朴な "m${index}" 割り当てだと id が衝突し
    DOT/Mermaid 上で別々の 2 ノードが同一ノードとして描画されて
    しまう。simple ノードの id 集合 (= それ自身の名前) を避けながら
    次の空き "m<n>" を順に割り当てることで衝突を防ぐ。
    */
    takenBySimple = simple;
    assignIds = idx: taken: names:
      if names == []
      then {}
      else let
        candidate = "m${toString idx}";
      in
        if builtins.elem candidate taken
        then assignIds (idx + 1) taken names
        else
          {${builtins.head names} = candidate;}
          // assignIds (idx + 1) (taken ++ [candidate]) (builtins.tail names);

    complexIds = assignIds 0 takenBySimple complex;
  in
    builtins.listToAttrs
    (map (n: {
        name = n;
        value =
          if isSimple n
          then n
          else complexIds.${n};
      })
      uniqueSorted);

  nodeNamesFromEdges = edges:
    lib.unique (lib.concatMap (e: [e.from e.to]) edges);

  # Build graph nodes from normalized/evaluated mulix modules.  Disabled nodes
  # remain present so graph output distinguishes "disabled" from "not in the
  # graph".  `config` is the evaluated module-system config.
  moduleNodes = {
    modules,
    config,
  }:
    map
    (mod: {
      name = mod.name;
      disabled = !(config.mulix.modules.${mod.name}.enable or false);
    })
    modules;

  renderNodeLabel = node:
    if node.disabled or false
    then "${node.name} (disabled)"
    else node.name;
in rec {
  inherit moduleNodes;

  /*
  escape: DOT / Mermaid の label に埋め込む文字列の最小限のエスケープ。
  (module 名 / configName は attrset key であり任意の文字列を取れる)
  */
  escape = s: builtins.replaceStrings ["\\" "\""] ["\\\\" "\\\""] s;

  /*
  toDot: Graphviz DOT 形式の文字列を返す。

  from --via--> to の module-to-module edge そのものを描画する。
  */
  toDot = {
    edges,
    nodes ? [],
    title ? "mulix dependency graph",
  }: let
    nodeNames = lib.unique (map (n: n.name) nodes ++ nodeNamesFromEdges edges);
    nodeMap = builtins.listToAttrs (map (n: {
        name = n.name;
        value = n;
      })
      nodes);
    ids = mkNodeIds nodeNames;

    nodeId = n: ids.${n} or (throw "mulix: internal error: missing node id for '${n}'");

    nodeLines =
      map
      (n: let
        node =
          nodeMap.${
            n
          } or {
            name = n;
            disabled = false;
          };
      in "  \"${nodeId n}\" [label=\"${escape (renderNodeLabel node)}\"];")
      nodeNames;

    edgeLines =
      map
      (e: "  \"${nodeId e.from}\" -> \"${nodeId e.to}\" [label=\"${escape e.via}\"];")
      edges;
  in
    lib.concatStringsSep "\n"
    ([
        "// ${title}"
        "// generated by mulix (graph.nix) — module-to-module dependency edges"
        "digraph mulix {"
        "  rankdir=LR;"
      ]
      ++ nodeLines
      ++ edgeLines
      ++ ["}"]);

  /*
  toMermaid: Mermaid flowchart 形式の文字列を返す。
  (GitHub / GitLab の markdown 内に直接埋め込める)

    graph LR
      niri["niri"] -->|wmconfig| waybar["waybar"]
  */
  toMermaid = {
    edges,
    nodes ? [],
    direction ? "LR",
  }: let
    nodeNames = lib.unique (map (n: n.name) nodes ++ nodeNamesFromEdges edges);
    nodeMap = builtins.listToAttrs (map (n: {
        name = n.name;
        value = n;
      })
      nodes);
    ids = mkNodeIds nodeNames;

    nodeId = n: ids.${n} or (throw "mulix: internal error: missing node id for '${n}'");

    nodeLines =
      map
      (n: let
        node =
          nodeMap.${
            n
          } or {
            name = n;
            disabled = false;
          };
      in "  ${nodeId n}[\"${escape (renderNodeLabel node)}\"]")
      nodeNames;

    edgeLines =
      map
      (e: "  ${nodeId e.from} -->|${escape e.via}| ${nodeId e.to}")
      edges;
  in
    lib.concatStringsSep "\n"
    (["graph ${direction}"]
      ++ nodeLines
      ++ edgeLines);

  /*
  toDotFile / toMermaidFile: Nix store に書き込んだファイルを返す。
  `builtins.toFile` を使用 (pure — nix-instantiate でも動作する)。
  */
  toDotFile = name: edges:
    builtins.toFile "mulix-${name}-deps.dot" (toDot {inherit edges;});

  toMermaidFile = name: edges:
    builtins.toFile "mulix-${name}-deps.mmd" (toMermaid {inherit edges;});

  /*
  toMarkdown: DOT/Mermaid コードブロックを含む markdown 文書を返す。
  */
  toMarkdown = {
    edges,
    nodes ? [],
    title ? "mulix dependency graph",
  }: let
    header = [
      "# ${title}"
      ""
      "Module-to-module declared dependencies (sender → configName → receiver)."
      ""
    ];
    mermaidBlock = [
      "```mermaid"
      (toMermaid {inherit edges nodes;})
      "```"
      ""
    ];
    edgeList =
      if edges == []
      then ["No declared dependencies."]
      else
        map
        (e: "- `${e.from}` sends **${e.via}** → read by `${e.to}`")
        edges;
  in
    lib.concatStringsSep "\n" (header ++ mermaidBlock ++ edgeList ++ [""]);
}
